### ISSUE TITLE
Convert numeric character types to numbers

### ISSUE THREAD

**Issue by wilml** [jack-laverty/arinc424#10]
Thank you for the contribution!

Reading through the ARINC-424 specification, there are a number of fields with character types set as numeric (e.g., 5.12 SEQ NR, 5.45 FREQ, etc).

Reading through the code it does not appear these string values are converted to numerics. Is it intentional to keep as strings? Would you be open to PRs to add this functionality? 

Perhaps we could add a flag to the Record class for conversions, default to False to make backwards compatible and propagate that to the decode function. Let me know your thoughts.

**Comment by jack-laverty** [comment]
No worries!

Always open to pull requests.

I don't think this change would break backwards compatibility, but I'm not fussed about that anyway. It's a work in progress.

**Comment by jack-laverty** [comment]
After thinking about this some more, I worry there are too many numeric values that would lose information if converted from a string to a numeric data type, like numeric fields with leading zeros or spaces. Not sure how to handle that yet.
